### ISSUE TITLE
Register order

### ISSUE THREAD

**Issue by arenadorn** [maxlklaxl/python-tsl2591#5]
Found an error, because I'm using this sensor for my bachelors degree.
You have to read the data from the CH0 register first, and then from the CH1 register. Otherwise in some cases, the value in CH1 will still be the old value (from the last read_data). I figured it out while testing the sensor with a white LED, changing the current through the LED and measuring the light  every 5s, it showed this behavior. In the data sheet they also recommend to read all registers in sequence, it has probably something to do with the shadow registers. So I changed the code as follows and now its working fine (I also put a bigger sleep time but I don't think thats the issue here):

```
def get_full_luminosity(self):
    self.enable()
    time.sleep(0.1*(self.integration_time+1.5))  # wait x ms for ADC to complete
    full = self.bus.read_word_data(
                self.sendor_address, COMMAND_BIT | REGISTER_CHAN0_LOW
                )
    ir = self.bus.read_word_data(
                self.sendor_address, COMMAND_BIT | REGISTER_CHAN1_LOW
                )
    self.disable()
    return full, ir
```

**Comment by maxlklaxl** [comment]
@arenadorn 
thx for pointing out this issue, would you like to file a pull request? else I would replace it.

**Comment by arenadorn** [comment]
@maxlklaxl thanks for the quick response, the request is filed
