### ISSUE TITLE
Interested in support for micropython on the ESP8266?

### ISSUE THREAD

**Issue by jfischer** [maxlklaxl/python-tsl2591#7]
I have an ESP8266 running [Micropython](http://docs.micropython.org/en/latest/esp8266/esp8266/quickref.html). I was able to use `python-tsl2591` to read data from the Lux sensor with a few minor changes. Micropython provides a lower-level interface to I2C. I implemented an SMBus emulation layer using this lower level API. This allowed me to use your code pretty directly, only changing the references to the `smbus` package.

Is this something you would be willing to include in your `python-tsl2591` distribution? I think auto-detection of the platform can be done via the `sys` module. If that approach works for you, I can clean up my code and prepare a patch request. Thanks!

**Comment by maxlklaxl** [comment]
Sounds interesting, but my main focus is to keep it as simple as possible
so that not so experienced users could understand it. But who about a fork?

**Comment by jfischer** [comment]
Max,
 Sure, I can fork the repo. I just wanted to check with you first to see if
you would like to incorporate the changes. It sounds like our goals are
slightly different - my goal is to support multiple platforms with the same
code base, making it easier for me to write multi-platform code in the
higher layers. When I have released my fork, I will put a pointer here in
case others are looking for something similar or in case you change your
mind. Thanks!

**Comment by jfischer** [comment]
My forked repo is at https://github.com/jfischer/micropython-tsl2591. It really does have to be a fork -- micropython on the ESP8266 is severely memory-limited. Just importing the tsl2591 module caused a memory error. I ended up having to condense the code (e.g. removing things like getter methods and comments). Thus, this is going to be a micropython-specific version. The good new is that it works great!

Thanks for your help and thanks for providing a nice base for me to work from in your python-tsl2591 module. I will try to port any changes you make to my version. Thanks!
